jobs:
  ci:
    name: Verify
    runs-on: ubuntu-20.04

    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      - name: Pull Tools
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Unit Tests
        run: ./ci/action

name: Action

on:
  schedule:
    - cron: "35 */6 * * *"
